version: '3.9'

services:
  db:
    container_name: postgres
    image: postgres:16-alpine@sha256:8a52533e6a945aaecf967402d49b91d6a501ffe3d71c00217b5486ac6d2e6353
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  cache:
    container_name: redis
    image: redis:7-alpine@sha256:090276da2603db19b154602c374f505d94c10ea57e9749fc3e68e955284bf0fd
    restart: always
    environment:
      - REDIS_PASSWORD=TEST
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
    ports:
      - 6379:6379
    volumes:
      - cache:/var/lib/redis/data

volumes:
  pgdata:
  cache:
    driver: local
