version: '3.9'

name: strelitzia

volumes:
  pgdata:

networks:
  strelitzia-network:
    driver: bridge

services:
  database:
    container_name: postgres
    image: postgres:16-alpine@sha256:17eb369d9330fe7fbdb2f705418c18823d66322584c77c2b43cc0e1851d01de7
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - strelitzia-network
    ports:
      - 5432:5432

  gynoecium:
    container_name: gynoecium
    image: ghcr.io/r34-strelitzia/gynoecium:latest
    restart: always
    environment:
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_ACCESS_EXPIRES_SECONDS: ${JWT_ACCESS_EXPIRES_SECONDS}
      JWT_REFRESH_EXPIRES_SECONDS: ${JWT_REFRESH_EXPIRES_SECONDS}
      DATABASE_URL: postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}/${DATABASE_NAME}?schema=public&application_name=gynoecium
    depends_on:
      - database
    networks:
      - strelitzia-network

  pistillum:
    container_name: pistillum
    image: ghcr.io/r34-strelitzia/pistillum:latest
    restart: always
    depends_on:
      - gynoecium
    networks:
      - strelitzia-network

  gateway:
    container_name: gateway
    image: nginx:1.25-alpine@sha256:bb193a04d4f2026c6342fc142741d8036a27ea89674830a0fd0569d58bb2ca77
    restart: always
    depends_on:
      - gynoecium
      - pistillum
    networks:
      - strelitzia-network
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
