name: Check

on: push

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        name: Install Dependencies
        with:
          node-version: 20
          cache: pnpm
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build
