name: Lint
on: push
jobs:
  lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: pnpm install
      - run: npx nx run-many --target=lint --all=true
