name: Lint
on: push
jobs:
  lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with:
          node-version: 18
          cache: pnpm
      - run: pnpm install
      - run: pnpm lint
